BEGIN TRANSACTION;

INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win2000', '5.0', 'Windows 2000', 64, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win2000', '5.01', 'Windows 2000', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win2000', '5.0', 'Windows 2000', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinXP', '5.1', 'Windows XP', 64, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinXP', '5.1', 'Windows XP', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinXP', '5.2', 'Windows XP', 64, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinXP', '5.2', 'Windows XP', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinVista', '6.0', 'Windows Vista', 64, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinVista', '6.0', 'Windows Vista', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win7', '6.1', 'Windows 7', 64, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win7', '6.1', 'Windows 7', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win8', '6.2', 'Windows 8', 64, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win8', '6.2', 'Windows 8', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Linux', '', 'Linux', 32, 'Linux Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win32', '', 'Windows', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('MacOSX', '10', 'Mac OS X', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinNT', '', 'Windows NT', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win95', '95', 'Windows 95', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Linux', '', 'Linux', 64, 'Linux Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('ChromeOS', '', 'Google Chrome OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinNT', '4.0', 'Windows NT', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win8.1', '6.3', 'Windows 8.1', 64, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win8.1', '6.3', 'Windows 8.1', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('MacOSX', '10.4', 'Mac OS X', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('MacOSX', '10.5', 'Mac OS X', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('MacOSX', '10.6', 'Mac OS X', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('MacOSX', '10.7', 'Mac OS X', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('MacOSX', '10.8', 'Mac OS X', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('MacOSX', '10.9', 'Mac OS X', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('MacOSX', '10.10', 'Mac OS X', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('CentOS', '', '', 32, '');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win98', '98', 'Windows 98', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinNT', '4.1', 'Windows NT', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('FreeBSD', '', 'FreeBSD', 32, 'FreeBSD Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '8.0', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '4.4', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '7.1', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Amiga OS', '', '', 32, 'Amiga');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WyderOS', '', '', 0, '');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win16', '', 'Windows', 16, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Darwin', '', 'Darwin is a Core Component of MacOSX and iOS', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '5.1', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '6.0', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '6.1', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '7.0', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Ubuntu', '12.04', 'Ubuntu Linux', 32, 'Canonical Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Ubuntu', '', 'Ubuntu Linux', 32, 'Canonical Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Ubuntu', '12.04', 'Ubuntu Linux', 64, 'Canonical Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Ubuntu', '', 'Ubuntu Linux', 64, 'Canonical Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '5.0', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinME', 'ME', 'Windows ME', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '2.3', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '4.0', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '4.1', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '4.2', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '4.3', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win10', '6.4', 'Windows 10', 64, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win10', '6.4', 'Windows 10', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win10', '10', 'Windows 10', 64, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win10', '10', 'Windows 10', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '3.0', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '3.1', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '3.2', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '4.0', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '4.1', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '4.2', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '4.3', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '5.0', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '8.1', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '8.2', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '1.0', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '1.1', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '1.5', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '1.6', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '2.0', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '2.1', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '2.2', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '3.0', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '3.1', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android', '3.2', 'Android OS', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Android for GoogleTV', '3.2', 'Android OS for GoogleTV', 32, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('MeeGo', '', 'Linux Smartphone OS', 32, 'Linux Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Darwin', '10', 'Darwin is a Core Component of MacOSX and iOS', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Brew', '2.0', 'Qualcomm Brew', 32, 'Qualcomm');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Bada', '2.0', 'Samsung Bada', 32, 'Samsung');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Bada', '1.2', 'Samsung Bada', 32, 'Samsung');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Bada', '1.0', 'Samsung Bada', 32, 'Samsung');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinNT', '3.1', 'Windows NT', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('JAVA', '', '', 32, 'Oracle');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('ChromeOS', '', 'Google Chrome OS', 64, 'Google Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinPhone8.1', '8.1', 'Windows Phone OS 8.1', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinPhone7.5', '7.5', 'Windows Phone OS 7.5', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinPhone6', '6.5', 'Windows Phone OS 6.5', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Brew', '3.1', 'Qualcomm Brew', 32, 'Qualcomm');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('BSD', '', 'BSD Four', 32, 'University of California, Berkeley');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('CellOS', '', '', 32, 'Sony');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('SymbianOS', '', 'Symbian OS', 32, 'Symbian Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinMobile', '', 'Windows Mobile OS', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinCE', '', 'Windows CE', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Linux Smartphone OS', '', 'Linux Smartphone OS', 32, 'Linux Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('SunOS', '', 'SunOS', 32, 'Oracle');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinPhone', '', 'Windows Phone OS', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('webOS', '2.1', 'HP webOS', 32, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('webOS', '', 'HP webOS', 32, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('webOS', '1.0', 'HP webOS', 32, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('webOS', '1.1', 'HP webOS', 32, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('webOS', '1.2', 'HP webOS', 32, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('webOS', '1.3', 'HP webOS', 32, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('webOS', '1.4', 'HP webOS', 32, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('webOS', '2.0', 'HP webOS', 32, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('webOS', '2.2', 'HP webOS', 32, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('webOS', '3.0', 'HP webOS', 32, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('MacPPC', '10', 'Mac OS X', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '2.0', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '2.1', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '2.2', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('NetBSD', '', 'NetBSD', 32, '');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('OpenBSD', '', 'OpenBSD', 32, '');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('OS/2', '', 'OS/2', 32, 'IBM');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('OpenVMS', '', 'OpenVMS', 32, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('CygWin', '', '', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('AIX', '', 'AIX', 32, 'IBM');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('BeOS', '', 'BeOS', 32, 'Access');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Tru64 UNIX', '', 'Tru64 UNIX', 64, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('HP-UX', '', 'HP-UX', 32, 'HP');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('IRIX64', '', 'IRIX64', 64, 'SGI');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RISC OS', '', 'RISC OS', 32, '');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Solaris', '', 'Solaris', 32, 'Oracle');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '10.3', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '10.2', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '10.1', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '10.0', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '7.1', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '7.0', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '6.0', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '5.0', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '4.7', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '4.6', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '4.5', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '4.3', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '4.2', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '4.1', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '4.0', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '3.8', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '3.7', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM OS', '3.6', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM Tablet OS', '1.0', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM Tablet OS', '2.1', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('RIM Tablet OS', '2.0', 'RIM OS', 32, 'Research In Motion Limited');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win31', '3.1', 'Windows 3.1', 16, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Mac68K', '10', 'Mac OS X', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Debian', '', 'Debian Linux', 32, 'Debian');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('PalmOS', '', '', 32, 'Palm');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinRT8', '6.2', 'Windows RT 8', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinRT8.1', '6.3', 'Windows RT 8.1', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win31', '3.11', 'Windows 3.11', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinNT', '3.5', 'Windows NT', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('FirefoxOS', '', 'Android OS', 32, 'Mozilla Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinNT', '', 'Windows NT', 64, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('FreeBSD', '', 'FreeBSD', 64, 'FreeBSD Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Unix', '', 'Unix', 32, '');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Ubuntu', '8.04', 'Ubuntu Linux', 32, 'Canonical Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Ubuntu', '10.04', 'Ubuntu Linux', 32, 'Canonical Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Ubuntu', '8.04', 'Ubuntu Linux', 64, 'Canonical Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Ubuntu', '10.04', 'Ubuntu Linux', 64, 'Canonical Foundation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('DragonFly BSD', '', 'DragonFlyBSD', 32, '');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinPhone7', '7.0', 'Windows Phone OS 7', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('WinPhone8', '8.0', 'Windows Phone OS 8', 32, 'Microsoft Corporation');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('PalmOS', '3.0', '', 32, 'Palm');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('iOS', '10', 'iPod, iPhone & iPad', 32, 'Apple Inc');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Brew', '3.0', 'Qualcomm Brew', 32, 'Qualcomm');
INSERT INTO sistemas_operativos (nombre, version, descripcion, bits, propietario) VALUES ('Win31', '3.11', 'Windows 3.11', 16, 'Microsoft Corporation');

COMMIT;